services:
  app:
    build: .
    container_name: tyoq-app
    env_file: .env
    tty: true
    stdin_open: true
    volumes:
      - ./app/main.py:/app/main.py
      - ./data/seed.db:/app/data/seed.db
